version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: rental_db
      MYSQL_USER: rental_user
      MYSQL_PASSWORD: rental_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command:
      - sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db

volumes:
  db_data: