# Generated by Django 5.2.1 on 2025-06-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={},
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listing_images/'),
        ),
    ]
